### ISSUE TITLE
sodacan example gives: No value for uninitialized NumericValue object r

### ISSUE THREAD

**Issue by mohanadkaleia** [pyomo-annex/pyomo_simplemodel#1]
Hello, 
I was trying to run the example of non-linear problem in this page: 

http://pyomocontrib-simplemodel.readthedocs.io/en/latest/sodacan.html#simplemodel-formulation

But after running it I got the following error: 

> WARNING: Loading a SolverResults object with a warning status into model=unknown;
> 	message from solver=<undefined>
> Status = other
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-9-6cda721bf631> in <module>()
>      16 print("Status = %s" % status.solver.termination_condition)
>      17 
> ---> 18 print("%s = %f" % (r, value(r)))
>      19 print("%s = %f" % (h, value(h)))
>      20 print("Objective = %f" % value(m.objective()))
> 
> /home/mohanad/anaconda2/lib/python2.7/site-packages/pyomo/core/kernel/numvalue.pyc in value(obj, exception)
>     168     if exception and (tmp is None):
>     169         raise ValueError("No value for uninitialized NumericValue object %s"
> --> 170                          % (obj.name,))
>     171     return tmp
>     172 
> 
> ValueError: No value for uninitialized NumericValue object r

What is the problem?

**Comment by whart222** [comment]
Perhaps the ipopt solver is not available?  I can't quite tell from the
error message.  Can you confirm?

**Comment by mohanadkaleia** [comment]
Yes, IPOPT is installed correctly, when I type ipopt in the command line it recognize it:

![image](https://user-images.githubusercontent.com/3438755/32613965-ce7896f6-c531-11e7-96a2-436899e66dff.png)

**Comment by mohanadkaleia** [comment]
I tried another pyomo example, and it gave me similar error: 

> Ipopt 3.12.8: 
> Exception of type: OPTION_INVALID in file "../../../../Ipopt/src/Algorithm/IpAlgBuilder.cpp" at line 271:
>  Exception message: Selected linear solver MA27 not available.
> Tried to obtain MA27 from shared library "libhsl.so", but the following error occured:
> libhsl.so: cannot open shared object file: No such file or directory
> 
> EXIT: Invalid option encountered.
> WARNING: Loading a SolverResults object with a warning status into model=unknown;
> 	message from solver=<undefined>
> ()
> *** Solution *** :
> Traceback (most recent call last):
>   File "pyomo_example.py", line 15, in <module>
>     print('x:', value(model.x))
>   File "/home/mohanad/anaconda2/lib/python2.7/site-packages/pyomo/core/kernel/numvalue.py", line 170, in value
>     % (obj.name,))
> ValueError: No value for uninitialized NumericValue object x
> 

Any clue about the problem? 
Thank you

**Comment by mohanadkaleia** [comment]
I figured out the problem, I had to add the libhsl.so librray into the shared library LD_LIBRARY_PATH 
first the name of it was libcoinhsl.so and IPOPT was looking for libhsl.so so I had to create a link to the new name: 
`ls -s libcoinhsl.so libhsl.so`

Then I had to add the location of hsl directory to the LD_LIBRARY_PATH, and now it is working fine :) 
Thanks

**Comment by Elenagh93** [comment]
Hi @mohanadkaleia and @whart222 
I have exactly the same problem in my optimization code. And I installed IPOPT in my anaconda, but nothing has solved. Could you please help me how can I solve this error?
This is the ERROR: evaluating object as numeric value: r[1,1]
        (object: <class 'pyomo.core.base.var._GeneralVarData'>)
    No value for uninitialized NumericValue object r[1,1]
Thank you in advance for your help.
Best,
Elnaz
