### ISSUE TITLE
Binary variables takes continues values after running the optimizer

### ISSUE THREAD

**Issue by mohanadkaleia** [pyomo-annex/pyomo_simplemodel#2]
Hello, 
I run the example of newsvendor problem from this page: 
http://pyomocontrib-simplemodel.readthedocs.io/en/latest/newsvendor.html#simplemodel-formulation

But the results are not binary, here: 
> Status = optimal
> x[hammer] = 1.000000
> x[screwdriver] = 1.000000
> x[towel] = 1.000000
> x[wrench] = 0.285714
> Objective = 25.857143

Why x[wrench] took 0.28 although the x defined as a binary? 

Note I used ipopt for the solver
Thank you

**Comment by whart222** [comment]
The ipopt solver does not directly handle binary variables.  Instead, when
you send a model with binary variables to ipopt it relaxes the integrality
constraint by using a continuous variable with bounds 0 and 1.

**Comment by mohanadkaleia** [comment]
:( I wasted a whole day to compile ipopt 
Do you have suggestions for a solver that can handle non-linear problems and support binary variables? 

Thanks

**Comment by whart222** [comment]
There isn't a single "best" solver for MINLP problems.  COIN-OR includes pre-built binaries for the Couenne solver.
